# Configuration de déploiement
project: cdn-template

# Commandes de build - Liste de commandes à exécuter pour préparer les fichiers
build:
  - echo Building project...
  - build
  # - pnpm run build
  # - composer install

# Liste des déploiements
deploy:
  - url: https://example.com/file.php
    localDir: ./
    remoteDir: /
    paths: [file.ext , dir]
    excludes: [file.ext , dir]
